import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import AffiliateSection from "@/components/affiliatesection";
import FeaturesSection from "@/components/featuressection";
import AffiliateSteps from "@/components/affiliatesteps";
import AffiliateCTA from "@/components/affiliatecta";
import Footer from "@/components/footer";
import FAQSection from "@/components/faqsection";
import { Space_Grotesk } from "next/font/google";

const spacegrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spacegrotesk} antialiased`}>
        <Navbar />
        <AffiliateSection />
        <FeaturesSection />
        <AffiliateSteps />
        <AffiliateCTA />
        <FAQSection />
        <Footer />
        {children}
      </body>
    </html>
  );
}
