import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";

import Footer from "@/components/footer";
import { Space_Grotesk } from "next/font/google";

const spacegrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spacegrotesk} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
