import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import AffiliateSection from "@/components/affiliatesection";
import FeaturesSection from "@/components/featuressection";
import AffiliateSteps from "@/components/affiliatesteps";
import AffiliateCTA from "@/components/affiliatecta";
import Footer from "@/components/footer";
import FAQSection from "@/components/faqsection";

const SpaceGroteskSans = localFont({
  src: "./fonts/SpaceGrotesk-VariableFont_wght.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const SpaceGroteskMono = localFont({
  src: "./fonts/SpaceGrotesk-VariableFont_wght.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SpaceGroteskSans.variable} ${SpaceGroteskMono.variable} antialiased`}
      >
        <Navbar />
        <AffiliateSection />
        <FeaturesSection />
        <AffiliateSteps />
        <AffiliateCTA />
        <FAQSection />
        <Footer />
        {children}
      </body>
    </html>
  );
}
